### ISSUE TITLE
Brute Ratel C4

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#12]
**Description**
Detection of Brute Ratel C4 Servers ( hxxps://bruteratel[.]com/ ) 

**Censys Search Query**
A query written in the [Brute Ratel C4 Server](https://search.censys.io/search?resource=hosts&q=services.http.response.body_hash%3D%22sha1%3A1a279f5df4103743b823ec2a6a08436fdf63fe30%22).

```
services.http.response.body_hash="sha1:1a279f5df4103743b823ec2a6a08436fdf63fe30"
```

**Comment by thehappydinoa** [comment]
This is really cool work! Thanks for your submissions!

**Comment by drb-ra** [comment]
Thank you! Censys data is pivotal to the value we offer the security community. I will actually merge one of your queries for Sliver C2 to the feeds, if that's OK with you.

**Comment by thehappydinoa** [comment]
I am so glad! And you can actually merge both of them in if you are interested. Just make sure to follow the format! And if there is a good example screenshot please add it!

Thanks!

**Comment by drb-ra** [comment]
Thank you! Better than a screenshot, I think! :-) I share regular twice daily updated results for free here https://github.com/drb-ra/C2IntelFeeds/tree/master/feeds/unverified mostly based you queries your have or very similar ones. 

It also uses your Python API module that makes life extremely easy.

**Comment by thehappydinoa** [comment]
Added in 5a24af8
