### ISSUE TITLE
Empire C2

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#13]
**Description**
Empire C2 Servers ( hxxps://bc-security[.]gitbook[.]io/empire-wiki/ )

**Censys Search Query**
[Empire C2](https://search.censys.io/search?resource=hosts&q=same_service%28services.http.response.body_hash%3A+%22sha1%3Abc517bf173440dad15b99a051389fadc366d5df2%22+AND+services.http.response.headers.expires%3A+0+and+services.http.response.headers.cache_control%3A+%22*%22%29).

```
same_service(services.http.response.body_hash: "sha1:bc517bf173440dad15b99a051389fadc366d5df2" AND services.http.response.headers.expires: 0 and services.http.response.headers.cache_control: "*")
```

**Comment by thehappydinoa** [comment]
Thank you for your submission! I will add it shortly!

**Comment by thehappydinoa** [comment]
Added in 5a24af8
