### ISSUE TITLE
RecordBreaker C2 aka Raccoon Stealer

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#15]
**Description**
RecordBreaker aka Raccoon Stealer v2 C2 servers, based on this tweet - https://twitter.com/1zrr4h/status/1593377638504087553

**Censys Search Query**
Raccoon Stealer V2 aka [RecordBreaker C2](https://search.censys.io/search?q=services.banner_hashes%3D%22sha256%3A7987d0c39c4839572ab88c6d82da01395f74e0c31f12d94c58d0e1bed0b0c75c%22&resource=hosts).

```
services.banner_hashes="sha256:7987d0c39c4839572ab88c6d82da01395f74e0c31f12d94c58d0e1bed0b0c75c"
```

**Additional context**
A quick validation based on tweet details and URL confirm a good percentage does return a DLL from that location.

**Comment by thehappydinoa** [comment]
Added in 5a24af8
