### ISSUE TITLE
Nighthawk C2

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#17]
**Description**
Detect [Nighthawk C2] (https://www.mdsec.co.uk/nighthawk/) Servers 

**Censys Search Query**
[Nighthawk C2 Servers]( https://search.censys.io/search?resource=hosts&q=same_service%28services.banner%3D%22HTTP%2F1.1+404+Not+Found%5Cr%5CnDate%3A++%3CREDACTED%3E%5Cr%5CnX-Test%3A+2%5Cr%5CnServer%3A+Apache%5Cr%5CnContent-Length%3A+20%5Cr%5Cn%22+and+services.http.response.body_hashes%3D%22sha256%3Ad872e8e4176213ea84ebc76d8fb621c31b4ca116fd0a51258813e804fe110ca4%22%29 ).

```dsl
same_service(services.banner="HTTP/1.1 404 Not Found\r\nDate:  <REDACTED>\r\nX-Test: 2\r\nServer: Apache\r\nContent-Length: 20\r\n" and services.http.response.body_hashes="sha256:d872e8e4176213ea84ebc76d8fb621c31b4ca116fd0a51258813e804fe110ca4")
```

**Additional context**
Reference: No longer available.

**Comment by thehappydinoa** [comment]
Thank you! I will add it this weekend, I can actually make this query more specific too.

**Comment by drb-ra** [comment]
Thank you! Go for it, would love to learn how to make these better.

**Comment by drb-ra** [comment]
@thehappydinoa can you please hold from publishing and close this issue for now, the reference tweet has been deleted.

**Comment by thehappydinoa** [comment]
@drb-ra Here is the Shodan link from that tweet: https://www.shodan.io/search?query=HTTP%2F1.1+404+Not+Found+Date%3A+GMT+X-Test%3A+2+Server%3A+Apache+Content-Length%3A+20+http.html_hash%3A-1434675441

**Comment by drb-ra** [comment]
Send you a DM on Twitter, easier to clarify there.
