### ISSUE TITLE
NimPlant C2 Detection

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#21]
**Description**
Detect NimPlant C2 Servers - https://github.com/chvancooten/NimPlant 

The body hash part of the query, while the body seems fairly generic the hits right now all match the same servers so it could prove an additional method of detection for the cases where a reverse proxy is used to hide the server header.

**Censys Search Query**
[NimPlant C2](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=INCLUDE&q=services.http.response.headers.Server%3D%22NimPlant+C2+Server%22+OR+services.http.response.body_hashes%3D%22sha256%3A636d68bd1bc19d763de95d0a6406f4f77953f9973389857353ac445e2b6fff87%22).

```dsl
services.http.response.headers.Server="NimPlant C2 Server" OR services.http.response.body_hashes="sha256:636d68bd1bc19d763de95d0a6406f4f77953f9973389857353ac445e2b6fff87"
```

**Additional context**
Reference: https://twitter.com/chvancooten/status/1629911090774589442

**Comment by thehappydinoa** [comment]
Just added this and a couple others! Thanks for adding!
