### ISSUE TITLE
PupyRAT

### ISSUE THREAD

**Issue by drb-ra** [thehappydinoa/awesome-censys-queries#26]
**Description**
[Pupy RAT](https://github.com/n1nj4sec/pupy) C2 Detection

**Censys Search Query**
[Pupy RAT Hosts](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=100&virtual_hosts=EXCLUDE&q=services.http.response.headers.Etag%3D%22%5C%22aa3939fc357723135870d5036b12a67097b03309%5C%22%22)

```dsl
services.http.response.headers.Etag="\"aa3939fc357723135870d5036b12a67097b03309\""
```

**Additional context**
https://twitter.com/i/web/status/1654038602282565632

**Comment by drb-ra** [comment]
Final version:

[Pupy RAT Hosts](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=100&virtual_hosts=EXCLUDE&q=same_service%28services.http.response.headers.Etag%3D%22%5C%22aa3939fc357723135870d5036b12a67097b03309%5C%22%22+AND+services.http.response.headers.Server%3D%22nginx%2F1.13.8%22%29+OR+same_service%28services.tls.certificates.leaf_data.issuer.organization%3A%2F%5Ba-zA-Z%5D%7B10%7D%2F+AND++services.tls.certificates.leaf_data.subject.organization%3A%2F%5Ba-zA-Z%5D%7B10%7D%2F+AND+services.tls.certificates.leaf_data.subject.organizational_unit%3D%22CONTROL%22%29)

```same_service(services.http.response.headers.Etag="\"aa3939fc357723135870d5036b12a67097b03309\"" AND services.http.response.headers.Server="nginx/1.13.8") OR same_service(services.tls.certificates.leaf_data.issuer.organization:/[a-zA-Z]{10}/ AND  services.tls.certificates.leaf_data.subject.organization:/[a-zA-Z]{10}/ AND services.tls.certificates.leaf_data.subject.organizational_unit="CONTROL")```

**Comment by thehappydinoa** [comment]
Added in 04191558b4b3b24a07c265ba7cb534200554f978
